In [35]:
# numpy is the library that allows for the use of arrays and matrices in python 
import numpy as np

In [36]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [37]:
type(a)

numpy.ndarray

BASIC OPERATIONS OF ARRAY

In [38]:
print(a+b)
print(a-b)
print(a*b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [39]:
# creating a 2D array
a =  np.array([[1,2],[3,4]])
print(a)


[[1 2]
 [3 4]]


In [40]:
# creating 3D array
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [41]:
print(b.shape)

(2, 2, 2)


In [42]:
print(a.ndim)

2


In [43]:
print(b.ndim)

3


In [44]:
print(a.dtype)

int64


In [45]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [47]:
np.random.randint(10,30, size=(3,3))

array([[20, 19, 28],
       [18, 26, 15],
       [10, 14, 29]], dtype=int32)

In [48]:
x = np.array([[7,2,3],
            [2,5,2],
            [3,5,1]])
y = np.array([[1,8,7],
              [3,7,2],
              [2,5,3]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 7]
 [3 7 2]
 [2 5 3]]


In [49]:
print(x*y)

[[ 7 16 21]
 [ 6 35  4]
 [ 6 25  3]]


In [50]:
print(x.dot(y)) # matrix multiplicatiom

[[19 85 62]
 [21 61 30]
 [20 64 34]]


In [51]:
print(x@y)

[[19 85 62]
 [21 61 30]
 [20 64 34]]


In [52]:
x.prod() # it gives multiplication of all the elements of the array

np.int64(12600)

In [54]:
x.mean() # it gives the mean of all the elements of the array

np.float64(3.3333333333333335)

In [55]:
x.mean(axis=0) # it gives the mean of each colomns

array([4., 4., 2.])

In [57]:
x.mean(axis=1) #it gives the mean of each row 

array([4., 3., 3.])

In [59]:
print(x.sum()) # it gives the sum of all the elements of the array
print(x.var()) # it gives the variance of all the elements of the array
print(x.std()) # it gives the standard  deviation of all the elements of the array

30
3.3333333333333335
1.8257418583505538


In [60]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a, 25)) # it gives the 25the percentile of the array
print(np.percentile(a, 50)) # it gives the 50th percentile of the array
print(np.percentile(a, 75)) # it gives the 75th percentile of the array

3.0
5.0
7.0


In [74]:
arr = np.random.randint(10,50, size=(4,4))
print(arr)

[[13 33 38 44]
 [48 24 29 45]
 [12 36 30 48]
 [19 30 30 38]]


In [79]:
print('2x8')
print(arr.reshape(2,8))

2x8
[[13 33 38 44 48 24 29 45]
 [12 36 30 48 19 30 30 38]]


In [78]:
print(arr.reshape(8,2))

[[13 33]
 [38 44]
 [48 24]
 [29 45]
 [12 36]
 [30 48]
 [19 30]
 [30 38]]


In [80]:
print(x)

[[7 2 3]
 [2 5 2]
 [3 5 1]]


In [82]:
print(x[0])
print(x[0,0])

[7 2 3]
7


In [86]:
print(x[:3])
print(x[2:])

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[3 5 1]]
